using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

namespace ca3
{
    public class Currencycon
    {
        public double ada { get; set; }
        public double aed { get; set; }
        public double afn { get; set; }
        public double all { get; set; }
        public double amd { get; set; }
        public double ang { get; set; }
        public double aoa { get; set; }
        public double ars { get; set; }
        public double aud { get; set; }
        public double awg { get; set; }
        public double azn { get; set; }
        public double bam { get; set; }
        public double bbd { get; set; }
        public double bch { get; set; }
        public double bdt { get; set; }
        public double bgn { get; set; }
        public double bhd { get; set; }
        public double bif { get; set; }
        public double bmd { get; set; }
        public double bnb { get; set; }
        public double bnd { get; set; }
        public double bob { get; set; }
        public double brl { get; set; }
        public double bsd { get; set; }
        public double btc { get; set; }
        public double btn { get; set; }
        public double bwp { get; set; }
        public double byn { get; set; }
        public double byr { get; set; }
        public double bzd { get; set; }
        public double cad { get; set; }
        public double cdf { get; set; }
        public double chf { get; set; }
        public double clf { get; set; }
        public double clp { get; set; }
        public double cny { get; set; }
        public double cop { get; set; }
        public double crc { get; set; }
        public double cuc { get; set; }
        public double cup { get; set; }
        public double cve { get; set; }
        public double czk { get; set; }
        public double djf { get; set; }
        public double dkk { get; set; }
        public double doge { get; set; }
        public double dop { get; set; }
        public double dzd { get; set; }
        public double egp { get; set; }
        public double ern { get; set; }
        public double etb { get; set; }
        public double etc { get; set; }
        public double eth { get; set; }
        public double eur { get; set; }
        public double fjd { get; set; }
        public double fkp { get; set; }
        public double gbp { get; set; }
        public double gel { get; set; }
        public double ggp { get; set; }
        public double ghs { get; set; }
        public double gip { get; set; }
        public double gmd { get; set; }
        public double gnf { get; set; }
        public double gtq { get; set; }
        public double gyd { get; set; }
        public double hkd { get; set; }
        public double hnl { get; set; }
        public double hrk { get; set; }
        public double htg { get; set; }
        public double huf { get; set; }
        public double idr { get; set; }
        public double ils { get; set; }
        public double imp { get; set; }
        public double inr { get; set; }
        public double iqd { get; set; }
        public double irr { get; set; }
        public double isk { get; set; }
        public double jep { get; set; }
        public double jmd { get; set; }
        public double jod { get; set; }
        public double jpy { get; set; }
        public double kes { get; set; }
        public double kgs { get; set; }
        public double khr { get; set; }
        public double kmf { get; set; }
        public double kpw { get; set; }
        public double krw { get; set; }
        public double kwd { get; set; }
        public double kyd { get; set; }
        public double kzt { get; set; }
        public double lak { get; set; }
        public double lbp { get; set; }
        public double link { get; set; }
        public double lkr { get; set; }
        public double lrd { get; set; }
        public double lsl { get; set; }
        public double ltc { get; set; }
        public double ltl { get; set; }
        public double lvl { get; set; }
        public double lyd { get; set; }
        public double mad { get; set; }
        public double mdl { get; set; }
        public double mga { get; set; }
        public double mkd { get; set; }
        public double mmk { get; set; }
        public double mnt { get; set; }
        public double mop { get; set; }
        public double mro { get; set; }
        public double mur { get; set; }
        public double mvr { get; set; }
        public double mwk { get; set; }
        public double mxn { get; set; }
        public double myr { get; set; }
        public double mzn { get; set; }
        public double nad { get; set; }
        public double ngn { get; set; }
        public double nio { get; set; }
        public double nok { get; set; }
        public double npr { get; set; }
        public double nzd { get; set; }
        public double omr { get; set; }
        public double pab { get; set; }
        public double pen { get; set; }
        public double pgk { get; set; }
        public double php { get; set; }
        public double pkr { get; set; }
        public double pln { get; set; }
        public double pyg { get; set; }
        public double qar { get; set; }
        public double ron { get; set; }
        public double rsd { get; set; }
        public double rub { get; set; }
        public double rwf { get; set; }
        public double sar { get; set; }
        public double sbd { get; set; }
        public double scr { get; set; }
        public double sdg { get; set; }
        public double sek { get; set; }
        public double sgd { get; set; }
        public double shp { get; set; }
        public double sll { get; set; }
        public double sos { get; set; }
        public double srd { get; set; }
        public double std { get; set; }
        public double svc { get; set; }
        public double syp { get; set; }
        public double szl { get; set; }
        public double thb { get; set; }
        public double theta { get; set; }
        public double tjs { get; set; }
        public double tmt { get; set; }
        public double tnd { get; set; }
        public double top { get; set; }
        public double trx { get; set; }
        public double @try { get; set; }
        public double ttd { get; set; }
        public double twd { get; set; }
        public double tzs { get; set; }
        public double uah { get; set; }
        public double ugx { get; set; }
        public double usd { get; set; }
        public double usdt { get; set; }
        public double uyu { get; set; }
        public double uzs { get; set; }
        public double vef { get; set; }
        public double vnd { get; set; }
        public double vuv { get; set; }
        public double wst { get; set; }
        public double xaf { get; set; }
        public double xag { get; set; }
        public double xau { get; set; }
        public double xcd { get; set; }
        public double xdr { get; set; }
        public double xlm { get; set; }
        public double xof { get; set; }
        public double xpf { get; set; }
        public double xrp { get; set; }
        public double yer { get; set; }
        public double zar { get; set; }
        public double zmk { get; set; }
        public double zmw { get; set; }
        public double zwl { get; set; }
    }
}
